export const menuItems = {
    'BASIC': [
      'Dashboard', 
      'Services', 
      'Default Security', 
      'Certificates', 
      'IP Configuration', 
      'Administration', 
      'Web Firewall Logs', 
      'Access Logs', 
      'Audit Logs', 
      'Notifications', 
      'Reports', 
      'Azure Configuration', 
      'Online Help Search', 
      'Recommendations'
    ],
    'SECURITY POLICIES': [
      'Policy Manager', 
      'Request Limits', 
      'Cookie Security', 
      'URL Protection', 
      'Parameter Protection', 
      'Cloaking', 
      'Data Theft Protection', 
      'URL Normalization', 
      'Global ACLs', 
      'Client Profile', 
      'Tarpit', 
      'Risk Scores', 
      'Action Policy'
    ],
    'WEBSITES': [
      'Allow/Deny/Redirect', 
      'Website Profiles', 
      'Advanced Security', 
      'JSON Security', 
      'GraphQL Security', 
      'Web Socket Security', 
      'IP Reputation', 
      'URL Encryption', 
      'Website Translations', 
      'Trusted Hosts', 
      'Adaptive Profiling', 
      'Exception Profiling', 
      'Exception Heuristics', 
      'XML Validations', 
      'XML Protection', 
      'Traffic Management', 
      'FTP Security', 
      'Client Side Protection'
    ],
    'BOT MITIGATION': [
      'Bot Mitigation', 
      'Bot Spam Mitigation', 
      'Application DDoS Mitigation', 
      'Libraries'
    ],
    'ACCESS CONTROL': [
      'Authentication Services', 
      'Authentication Policies', 
      'Local Users/Groups', 
      'Client Certificates', 
      'Web Token Validation'
    ],
    'NETWORKS': [
      'NAT', 
      'Routes', 
      'ACL', 
      'Network Configuration', 
      'Network Firewall Logs'
    ],
    'ADVANCED': [
      'Backups', 
      'Energize Updates', 
      'Firmware Update', 
      'Export Logs', 
      'System Logs', 
      'Templates', 
      'View Internal Patterns', 
      'Libraries', 
      'Admin Access Control', 
      'High Availability', 
      'Appearance', 
      'System Configuration', 
      'Secure Administration', 
      'Troubleshooting', 
      'Vulnerability Reports', 
      'CloudGen Firewall Settings', 
      'Cloud Control', 
      'Task Manager'
    ],
    // Add more main menu items and their submenus as needed
  };
  